name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    name: Sync with Hugging face
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub
      - name: Login to Hugging Face Hub
        run: huggingface-cli login ${{ secrets.HG }}
      - name: Add remote
        env:
          HF: ${{ secrets.HG }}
        run: git remote add space https://MBIANDI:$HF@huggingface.co/spaces/MBIANDI/demo2
      - name: Push to hub
        env:
          HF: ${{ secrets.HG }}
        run: git push --force https://MBIANDI:$HF@huggingface.co/spaces/MBIANDI/demo2 main
